### ISSUE TITLE
WPAD search downto http://wpad/wpad.dat

### ISSUE THREAD

**Issue by snpk** [MarkusBernhardt/proxy-vole#14]
This is defined in Wikipedia as solution.
There is no security issue as with http://wpad.com/wpad.dat
Would be fine, if this is implemented in next version 1.0.4

**Comment by MarkusBernhardt** [comment]
Fixed. Will be in next release

**Comment by dbdr** [comment]
Shouldn't wpad.<tld> be skipped? That is, continue this loop when i == 1:
https://github.com/MarkusBernhardt/proxy-vole/blob/bc5780979402ed86c30a3e6bebc07f29d571dd80/src/main/java/com/github/markusbernhardt/proxy/search/wpad/WpadProxySearchStrategy.java#L130

I know it is not a complete solution (e.g. for wpad.co.<tld>), but it helps, and I suppose it would save a DNS query and therefore some time during initialization when no WPAD was found.

**Comment by MarkusBernhardt** [comment]
According to Wikipedia the following URLs should be checked:

http://wpad.department.branch.example.com/wpad.dat
http://wpad.branch.example.com/wpad.dat
http://wpad.example.com/wpad.dat
http://wpad/wpad.dat

This way the code is implemented right now.

**Comment by MarkusBernhardt** [comment]
Ah. I see your point

**Comment by MarkusBernhardt** [comment]
This is, what happens now:

http://wpad.department.branch.example.com/wpad.dat
http://wpad.branch.example.com/wpad.dat
http://wpad.example.com/wpad.dat
**http://wpad.com/wpad.dat**
http://wpad/wpad.dat

**Comment by MarkusBernhardt** [comment]
Is that really bad?

**Comment by dbdr** [comment]
Well, there is an associated security risk, which can be theoretically pretty bad, though this solution is not perfect, it covers part of it. The Wikipedia article call the current behaviour an "incorrect implementation".

The speedup might also not be huge but always nice to have.

Given that the change is pretty trivial, it seems worth it to me. Would you like me to send a pull request?

**Comment by MarkusBernhardt** [comment]
Sure. Go ahead ;-))

**Comment by dbdr** [comment]
What do you think of the PR?
