### ISSUE TITLE
Can proxy-vole read windows system settings?

### ISSUE THREAD

**Issue by NameetaJain** [MarkusBernhardt/proxy-vole#15]
Hi,

If I have a proxy set, which works with my windows credentials, does proxy-vole has functionality to read windows credentials automatically?

**Comment by phansson** [comment]
Hi. 
Proxy-vole is about (1) detecting a proxy and (2) then using it as per Java's concept of `ProxySelector`.

Proxy-vole is oblivious to how to actually authenticate with a proxy, unless the credentials are explicitly given. In Java terms authentication is the so-called [Authenticator](https://docs.oracle.com/javase/8/docs/api/java/net/Authenticator.html), which proxy-vole doesn't touch. Bottom line: This is outside the scope of proxy-vole.

So, in essence, your question is:  "Does the JRE know, out-of-the-box, how to authenticate seamlessly with a network proxy?". The answer to this question is somewhat complex, in particular on the Windows platform. To answer we would also need to know exactly which auth scheme your proxy uses.

In many corporate networks today the proxy is likely to use the Negotiate scheme for authentication (also known as SPNEGO). This implies the use of Kerberos behind your back. I'm guessing this is what your proxy is using. In principle this will work out of the box. Oracle implemented full support for that, I think it was in Java 1.6.  However, Microsoft later tightened the grip on how an application can get access to the so-called Kerberos session key which essentially meant the Oracle's way of doing things no longer worked, at least not without fiddling with registry keys. You can read more about it [here](https://stackoverflow.com/questions/14556119/how-do-people-make-java-spnego-client-work-in-windows). So, in principle this would all work nicely for you: behind the scenes there would be a seamless authentication going on with the proxy using your Windows credentials (more accurately your AD credentials). But in practice it doesn't work.

**Comment by NameetaJain** [comment]
Hi,

Thanks for replying. Can you please also consider issue #17 (Information
Request - Behavior of http and https proxy on Linux)?
It is just an information request, a bit critical in designing our solution.

Thanks & Regards,
Nameeta

**Comment by MarkusBernhardt** [comment]
As Chanson wrote authentication is outside the scope of this library. Therefore closing.
