### ISSUE TITLE
Information Request - Behavior of http and https proxy on Linux

### ISSUE THREAD

**Issue by NameetaJain** [MarkusBernhardt/proxy-vole#17]
Can you please explain why https is picked only on detection of http proxy on linux?

**Comment by phansson** [comment]
I'm not sure what you mean. The only place where proxy-vole use either http or https is if settings says to automatically detect proxy settings (meaning it says to use WPAD). If proxy-vole can detect that there's a PAC file somewhere on the network (it will do the detection using either DHCP or DNS) it will attempt to download this PAC file and it will do so using http, not https. Regardless of platform. Is this the phase you are referring to, i.e. the download of the PAC file ?

Anyway, apart from download of PAC file, proxy-vole isn't involved in any http vs https decision.

**Comment by NameetaJain** [comment]
My use case is for Linux (I tested on Ubuntu 14.04)
-  I have set **https_proxy** environment variable
   export https_proxy=https://10.164.0.0:3128
**Observation:**
- When application runs, proxy-vole looks for http_proxy environment variable, if it is not set, no environment variables are picked
- If I set both http_proxy and https_proxy environment variable, proxy-vole picks values of http, https and ftp also.

**Expected:**
If only **https_proxy** is set, it should also be picked up by library.

So, my question is, why library first checks for **http_proxy** environment variable, and if found then picks up other variables.

**Comment by phansson** [comment]
I agree with you in principle: if an environment variable is set then it should be respected by proxy-vole. If you set `https.proxyHost` env var then it should be respected, regardless if you have defined `http.proxyHost` too. 

However, setting the https env var without also setting the http env var seems like a corner case to me. I'm not sure it would ever reflect a real-life example.

**Comment by NameetaJain** [comment]
Thank you for your response. I also have one more query,
We have tested DNS from proxy-vole, it works fine. Does it also support DHCP?
I have read in logs, Searching per DHCP is not supported. What does that mean?

**Comment by phansson** [comment]
Your question about DHCP is a new question. Please open a new issue for that.

**Comment by NameetaJain** [comment]
Ok. Closing this issue. Thank you.
