### ISSUE TITLE
NullPointerException if PAC method returns null

### ISSUE THREAD

**Issue by techpavan** [MarkusBernhardt/proxy-vole#2]
Hi Markus,

I found one more issue that if a null is returned from PAC file method, we end in NPE at com.github.markusbernhardt.proxy.selector.pac.PacProxySelector.findProxy(PacProxySelector.java:128).

As per the [specification](https://web.archive.org/web/20070602031929/http://wp.netscape.com/eng/mozilla/2.0/relnotes/demo/proxy-live.html), a null is a valid return from method and it means that no proxy needs to be used. Please see if this can be fixed.

Thanks,
Pavan

**Comment by MarkusBernhardt** [comment]
Hi Pavan,
thanks for that catch.
It's fixed.
Markus

**Comment by MarkusBernhardt** [comment]
Fixed with release 1.0.2
