### ISSUE TITLE
Proxy-Vole does not find proxy

### ISSUE THREAD

**Issue by johnau** [MarkusBernhardt/proxy-vole#26]
I was working with de.rosstauscher.proxy_vole (4.0.0) which worked fine.
Decided to shift to this fork as it is more recent, but it does not detect the proxy using ANY strategy.  (The original proxy_vole was able to detect the proxy using 5 strategies.)

Is this still a functioning project?

**Comment by gschnepp** [comment]
Yes! And it works better than the old library. You must've made any mistake on implementation. If you don't think so, still feel the library is having a problem, please come back with more details on your settings.

**Comment by johnau** [comment]
Hmm very strange, I basically just swapped your library in place of the
original.   Code was working with the original fine, detected the http
proxy at my work.  Switched to yours and it would always say direct
connection (no proxy).  It simply could not see the http proxy at work.

**Comment by johnau** [comment]
I will have another crack with it though, i did try it out very briefly. If
i recreate the problem ill send something through

On Sun, Sep 24, 2017 at 9:59 PM, John McSweeney <john.mcsweeney.88@gmail.com

**Comment by gschnepp** [comment]
Maybe the proxy detected by the old library is not neccessary for the connection you're trying to establish? I mean, both libraries could be correct, from different point of views. As long as the result is the same (= it works!) it doesn't matter, correct?

**Comment by johnau** [comment]
Hi Markus, I can see what you are saying, however the proxy must be
detected to establish connection.
I will try again with your library (I would like to use the most up to date
fork, and if you have put in work I would like to make use of it and give
some credits to you!) --- and, as i said in my second, 1-liner email, I
tried your library very briefly, I will give it a proper go soon and let
you know if I recreate the issue and provide you with some useful
information :D

cheers
john

**Comment by MarkusBernhardt** [comment]
Hi johnau,
do you have any news on this? There were some bugs in the code we fixed with the upcoming release 1.0.4. Could you please retest the new version. Will close this issue for now. Please reopen it, when you have more information.
Markus
