### ISSUE TITLE
Not detecting issue while running tomcat as service

### ISSUE THREAD

**Issue by madhupmanihp** [MarkusBernhardt/proxy-vole#27]
Hi Markus,
Once we are running tomcat as service,it is not detecting any proxy.
is there any setting needs to change to detect the proxy while running tomcat as a service ?

**Comment by phansson** [comment]
I suppose by "service", you mean as a Service on Windows?
You'll need to read up on how proxy settings works from a Windows service count. The answer is out there, friend. It just requires a bit of Googling. This is unrelated to proxy-vole.

**Comment by MarkusBernhardt** [comment]
I also guess this is a windows problem and not a problem inside proxy-vole. Will close this ticket for now.
