### ISSUE TITLE
The original proxy-vole, merge and/or unfork?

### ISSUE THREAD

**Issue by jchamlin** [MarkusBernhardt/proxy-vole#3]
It appears that the original proxy-vole library has no binary releases since 2013, and the last commit was in 2015. https://code.google.com/archive/p/proxy-vole/source/default/commits

I have some questions/requests:

Are you monitoring changes in the original proxy-vole and pulling those changes in here?
What do you think of merging your changes back into the original project?
What do you think of completely unforking, and merging both projects back together?

**Comment by MarkusBernhardt** [comment]
Could you please give me a link to the original project you are referring to?
The one on google code is still dead.

**Comment by jchamlin** [comment]
I see you forked this in May of 2016. Sorry, I had not realized your fork was so recent. There have been no changes to the original proxy-vole since your fork. Closing this issue. Sorry for the noise. And thank you for taking up maintaining such a great library!

**Comment by MarkusBernhardt** [comment]
No problem and thanks for your input. If you find some problems or need some add ons please keep me informed.
