### ISSUE TITLE
jna: Can't find dependent libraries using WinHttpCurrentUserIEProxyConfig

### ISSUE THREAD

**Issue by jstammi** [MarkusBernhardt/proxy-vole#35]
Our auto-build fails for a test using proxy-vole for proxy detection **since using java 9.0.1** on a up-to-date windows 7 build slave:

`java.lang.UnsatisfiedLinkError: ...\jna--1712433994\jna5672512838192935606.dll: Can't find dependent libraries`

`java.lang.NoClassDefFoundError: Could not initialize class com.github.markusbernhardt.proxy.jna.win.WinHttpCurrentUserIEProxyConfig`

This is caused by using jna 4.2.2 being dynamically linked against `msvcrt100.dll`. This was reported and fixed for jna. It should be fixed for 4.3.0 I assume (most recent is 4.5.1; see https://github.com/java-native-access/jna/issues/636).

This does not become obvious with using java 1.8 as the dll is part of the 1.8 jre's.

Please upgrade your dependency to jna to a newer persion ... ?

**Comment by gschnepp** [comment]
This looks like the same problem I've reported here, on bullet 2: https://github.com/MarkusBernhardt/proxy-vole/issues/33 .

Thanks for pointing this out! I'm not yet able to fix it here, unfortunately.

**Comment by MarkusBernhardt** [comment]
Solved with release 1.0.5
