### ISSUE TITLE
Replace the Logger interface with an SLF4J reference, please

### ISSUE THREAD

**Issue by toolforger** [MarkusBernhardt/proxy-vole#37]
`com.github.markusbernhardt.proxy.util.Logger` is serving exactly the same purpose as SLF4J: a facade for the real logging backend. (LogBack and Log4J are logging backends, not logging facades like SLF4J and Logger.)
Footprint is not really a consideration: SLF4J itself is just 32k jar size; proxy-vole alone comes at 140k.
For projects that already use SLF4J, the size burden is really the other way round: they need an extra adapter class, in this case from `Logger` to SLF4J. It's actually a deterrent: A library that requires extra coding just to use it means an additional entry barrier.

**Comment by MarkusBernhardt** [comment]
Added a default Logger implementation using Slf4j.
Included in release 1.0.5
