### ISSUE TITLE
SocketException "Unknown proxy type : HTTP" on specific connections

### ISSUE THREAD

**Issue by gschnepp** [MarkusBernhardt/proxy-vole#4]
Software environment is:

- proxy-vole version is 1.0.2
- both Windows 10 64-bit and Windows 7 64-bit
- both Java 1.7.0.71 and Java 1.8.0.102.

I'm getting constant java.net.SocketExceptions "Unknown proxy type : HTTP" here, on specific complex proxy chains in minimum two of my customer's networks. They're operating big networks with thousands of users and cascading (chained) proxies, it seems.

I don't have problems in smaller environments with only one proxy or direct connections, and that's one of the curiosities: I'm having problems using the **automatic routines** on this complex environment only, using a FixedProxySelector is never a problem.

Please find test code and different outputs attached for

1. (not working) `ProxySearch.getDefaultProxySearch().getProxySelector()`
2. (not working) `new PacProxySelector(new UrlPacScriptSource("..."))`
3. (working) `new FixedProxySelector("...", 8080)`

I wont have access to this complex network for long, so please assist soon. I will support as good as possible, vice versa.

Guido

**Comment by gschnepp** [comment]
Now with attachments, too!  ;-)

[Output wrong using DefaultProxySearch.txt](https://github.com/MarkusBernhardt/proxy-vole/files/555783/Output.wrong.using.DefaultProxySearch.txt)
[Output wrong using PacProxySelector.txt](https://github.com/MarkusBernhardt/proxy-vole/files/555781/Output.wrong.using.PacProxySelector.txt)
[Output ok using FixedProxySelector.txt](https://github.com/MarkusBernhardt/proxy-vole/files/555782/Output.ok.using.FixedProxySelector.txt)
[InternetAccessTest.java.txt](https://github.com/MarkusBernhardt/proxy-vole/files/555784/InternetAccessTest.java.txt)

**Comment by gschnepp** [comment]
Sorry, bug in my own software. Found list of proxies is correct, but the right one was not selected correctly.
:-(

**Comment by MarkusBernhardt** [comment]
Hi Guido,
I'm back from vacation. If there is still something I can help you with, please contact me.
Best regards,
Markus

**Comment by gschnepp** [comment]
Hallo Markus,

Nein, alles gut. Der Fehler lag bei mir, Proxy-vole arbeitet wie gewünscht.

Da hatte ich den Fehler an der falschen Stelle vermutet. Die Ursache meines Problems war die Tatsache, dass der ProxySelector in den fraglichen Umgebungen tatsächlich eine Liste von Proxies zurückgibt, die ich nicht korrekt ausgewertet habe. Ich parse jetzt zunächst die Liste und nehme immer den ersten HTTP-Proxy‎. Generell habe ich aber kaum Beispielcode gefunden, wie man 'den richtigen' Proxy auswählt (.get(0) kann ja auch nicht immer die richtige Lösung sein, wie so oft in Beispielen gefunden).

Vielen Dank für dein Hilfsangebot! Ich war einfach zu schnell.

Gruß
Guido


Von: Markus Bernhardt
Gesendet: Samstag, 29. Oktober 2016 00:57
An: MarkusBernhardt/proxy-vole
Antwort an: MarkusBernhardt/proxy-vole
Cc: Guido Schnepp; State change
Betreff: Re: [MarkusBernhardt/proxy-vole] SocketException "Unknown proxy type : HTTP" on specific connections (#4)



Hi Guido,
I'm back from vacation. If there is still something I can help you with, please contact me.
Best regards,
Markus

**Comment by MarkusBernhardt** [comment]
Hallo Guido,

könntest Du evtl. Beispielscode bereitstellen, wie man den richtigen Proxy auswählt. Würde ich dann auf die Startseite packen.

Gruß und Dank,
Markus

**Comment by gschnepp** [comment]
Hallo Markus,

ich habe die Auswahl ‚des richtigen‘ Proxys in eine eigene Routine gepackt. Hier ist mein Code, mit englischen Kommentaren. Du kannst ihn gerne für die Website verwenden.

----------

import java.net.Proxy;
import java.net.ProxySelector;
import java.net.URI;
import java.util.List;

       private static Proxy findMyProxy(URI uri) {
             Proxy  proxy = Proxy.NO_PROXY;

             // Get list of proxies from default ProxySelector available for given URL
             List<Proxy>  proxies      = null;
             if (ProxySelector.getDefault() != null) {
                    proxies = ProxySelector.getDefault().select(uri);
             }

             // Find first proxy for HTTP/S. Any DIRECT proxy in the list returned is only second choice
             if (proxies != null && !proxies.isEmpty()) {
                    for (Proxy pxy : proxies) {
                           switch (pxy.type()) {
                           case HTTP:
                                  return pxy;

                           case DIRECT:
                                  proxy = pxy;
                                  break;

                           case SOCKS:
                                  break;       // Currently unsupported
                           }
                    }
             }

             // return DIRECT or NO proxy (being the same, more or less)
             return proxy;
       }

----------

Viele Grüße
Guido


Von: Markus Bernhardt [mailto:notifications@github.com]
Gesendet: Samstag, 29. Oktober 2016 21:46
An: MarkusBernhardt/proxy-vole <proxy-vole@noreply.github.com>
Cc: Guido Schnepp <Guido.Schnepp@cre-do.de>; State change <state_change@noreply.github.com>
Betreff: Re: [MarkusBernhardt/proxy-vole] SocketException "Unknown proxy type : HTTP" on specific connections (#4)


Hallo Guido,

könntest Du evtl. Beispielscode bereitstellen, wie man den richtigen Proxy auswählt. Würde ich dann auf die Startseite packen.

Gruß und Dank,
Markus

**Comment by MarkusBernhardt** [comment]
Hallo Guido,
herzlichen Dank für den Code!
Hab das README jetzt erweitert.
Gruß,
Markus

**Comment by gschnepp** [comment]
Cool! Labeled breaks (und continues) kannte ich noch nicht.
Wieder was gelernt. Danke!

Gruß
Guido



Von: Markus Bernhardt [mailto:notifications@github.com]
Gesendet: Donnerstag, 3. November 2016 15:27
An: MarkusBernhardt/proxy-vole <proxy-vole@noreply.github.com>
Cc: Guido Schnepp <Guido.Schnepp@cre-do.de>; State change <state_change@noreply.github.com>
Betreff: Re: [MarkusBernhardt/proxy-vole] SocketException "Unknown proxy type : HTTP" on specific connections (#4)


Hallo Guido,
herzlichen Dank für den Code!
Hab das README jetzt erweitert.
Gruß,
Markus

**Comment by gschnepp** [comment]
Mist, übersehen: Im switch() steht noch die Variable pxy, du weißt weiter unten aber die Variable p zu. Da müsste das switch noch angepasst werden.

Guido


Von: Guido Schnepp
Gesendet: Montag, 7. November 2016 10:42
An: 'MarkusBernhardt/proxy-vole' <reply@reply.github.com>
Betreff: AW: [MarkusBernhardt/proxy-vole] SocketException "Unknown proxy type : HTTP" on specific connections (#4)

Cool! Labeled breaks (und continues) kannte ich noch nicht.
Wieder was gelernt. Danke!

Gruß
Guido



Von: Markus Bernhardt [mailto:notifications@github.com]
Gesendet: Donnerstag, 3. November 2016 15:27
An: MarkusBernhardt/proxy-vole <proxy-vole@noreply.github.com<mailto:proxy-vole@noreply.github.com>>
Cc: Guido Schnepp <Guido.Schnepp@cre-do.de<mailto:Guido.Schnepp@cre-do.de>>; State change <state_change@noreply.github.com<mailto:state_change@noreply.github.com>>
Betreff: Re: [MarkusBernhardt/proxy-vole] SocketException "Unknown proxy type : HTTP" on specific connections (#4)


Hallo Guido,
herzlichen Dank für den Code!
Hab das README jetzt erweitert.
Gruß,
Markus

**Comment by MarkusBernhardt** [comment]
Uuups. Gefixt. Nice catch. Danke
