### ISSUE TITLE
Proxy-vole provoking sporadic crashes in ntdll

### ISSUE THREAD

**Issue by bogdanlupuro** [MarkusBernhardt/proxy-vole#43]
Using the proxy-vole library to do the proxy autodetection, it resulted in crashes while using the app. Furthermore, this only happened only the app was ahead-of-time precompiled with Excelsior JET. With the great help from the guys at Excelsior, they managed to isolate the issue as they describe below.

**Problem:**
**The proxy-vole library (proxy-vole-1.0.4.jar) has an issue provoking sporadic crashes in ntdll**

**Detailed description:**

> Specifically, it is in the com.github.markusbernhardt.proxy.jna.win.WTypes2#LPWSTRByReference class.
> 
> The default constructor of the class (through a chain of calls) allocates native memory with malloc BUT the allocated memory chunk is NOT zeroed so it contains undefined values.
> 
> Then, depending on execution path, the memory is either left intact or a pointer to a Windows system structure is stored there by a system call. In the latter case, Kernal32.GlobalFree() should be invoked later to free memory occupied by that Windows structure. This is implemented in LPWSTRByReference.finalize()
> 
> However, the finalizer cannot distinguish uninitialized (non-zeroed memory) from a pointer to the structure and always invokes GlobalFree, if the stored value is not null (0, zero, nil, you name it).
> 
> This provokes crashes in ntdll. 
> 
> Appearance of the problem is volatile because GlobalFree is invoked from a finalizer, which, in turn, can be invoked at different moments of execution or not invoked at all. 
> 
> Under Oracle JRE, the problem exists but does not appear due to a different order of invoking finalizers (the Java spec does not impose any particular order on it).

**Fix:**
A simple patch would be adding memory cleanup in the LPWSTRByReference constructor, which is added in the PR.

**Comment by MarkusBernhardt** [comment]
Fixed in release 1.0.5
