### ISSUE TITLE
Proxy-vole 1.0.5 not buildable with Java 10

### ISSUE THREAD

**Issue by gschnepp** [MarkusBernhardt/proxy-vole#48]
Hello,

due to an dependency issue with javadelight-nashorn-sandbox it's not possible to build even proxy-vole 1.0.5 acutally on Java 10. File structure has changed since Java 9 and therefore a hard-wired system dependency to tools.jar can'T be solved any longer. It's working up to Java 8.

Here is the javadelight issue report: https://github.com/javadelight/delight-nashorn-sandbox/issues/62

Regards
Guido

**Comment by gsmachado** [comment]
To make proxy-vole to work with Java 10, you can refer to the issue https://github.com/javadelight/delight-nashorn-sandbox/issues/62. :-)

**Comment by gschnepp** [comment]
Right! It was my own comment (see above).  ;-)  Closed there, but forgot to close here. Closing now...
