### ISSUE TITLE
Failed to find SOCKS proxy with Java search strategy

### ISSUE THREAD

**Issue by sake** [MarkusBernhardt/proxy-vole#5]
The Java Search strategy stops setting up the `ProxySelector` object when the property `http.proxyHost` is not set. That means if only `socksProxyHost` is set the search strategy will not create a selector for it.

I believe the guard checking the availability of the proxy properties should check for the presence of either of these properties. 
I can provide a patch if that is desired.

**Comment by MarkusBernhardt** [comment]
Thanks for that catch!

Would be great, if you could provide a patch. Is there an easy way to test that? Used the last SOCKS proxy 10 years ago.

**Comment by MarkusBernhardt** [comment]
I committed a fix. Could you perhaps verify it?

**Comment by sake** [comment]
The fix works fine. The proxy is returned by the ProxySelector object.

However there is another problem (might be worth to open another issue):
The SOCKS proxy is registered for the protocol scheme `socks`. The protocol scheme in the selector reflects the protocol of the proxied connection, not the connection to the proxy server. That means if I want to get a proxy for an HTTP connection, I have to request a http/https URI which can never return the SOCKS proxy, because the selector expects a socks:// URI.
I suppose a SOCKS proxy should be returned regardless of the URI used, because it is applicable to all TCP and UDP based connections.

Maybe the solution is to set the SOCKS proxy using the `setFallbackSelector` function in the `ProtocolDispatchSelector`. This time I attached the [patch](https://github.com/MarkusBernhardt/proxy-vole/files/603466/socks-fallback_patch.txt) directly.

Details on the intended meaning of the Java Proxy Variables can be found on the following link.
https://docs.oracle.com/javase/7/docs/technotes/guides/net/proxies.html

**Comment by MarkusBernhardt** [comment]
Ah. Ok. Thanks for adding the documentation. Now I understand it. Will look into it in the evening.

**Comment by sake** [comment]
Great. Thank you!

**Comment by sake** [comment]
Thanks again.

**Comment by MarkusBernhardt** [comment]
Thanks for your help!!!
Will push out a new release today.
